services:
  taskservice:
    build:
      context: ./TaskSystem  # Dit is de directory waar je .sln en Dockerfile zich bevinden
      dockerfile: TaskService/Dockerfile  # Specificeer de Dockerfile
    ports:
      - "5000:80"  # Expose port 80 van de container naar port 5000 op de host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Zet de omgeving als Development (optioneel)
  
  boardservice:
    build:
      context: ./BoardService  # Dit is de directory waar je .sln en Dockerfile zich bevinden
      dockerfile: BoardService/Dockerfile  # Specificeer de Dockerfile
    ports:
      - "5000:80"  # Expose port 80 van de container naar port 5000 op de host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Zet de omgeving als Development (optioneel)


