services:
  taskservice:
    build:
      context: ./TaskSystem  # De map waar de Dockerfile en het projectbestand zich bevinden
      dockerfile: TaskService/Dockerfile  # De naam van de Dockerfile
    ports:
      - "5000:80"  # Expose port 80 van de container naar port 5000 op de host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Zet de omgeving als Development (optioneel)

  boardservice:
    build:
      context: ./BoardService/BoardService  # De map waar de Dockerfile en het projectbestand zich bevinden
      dockerfile: Dockerfile  # De naam van de Dockerfile
    ports:
      - "5001:80"  # Expose port 80 van de container naar port 5001 op de host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Zet de omgeving als Development (optioneel)


  userservice:
    build:
      context: ./UserService/UserService  # Pad naar je UserService directory
      dockerfile: Dockerfile
    ports:
      - "5002:80"  # Poort configuratie, pas aan als dat nodig is
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Zet de omgeving als Development (optioneel)

  commentservice:
    build:
      context: ./CommentService/CommentService 
      dockerfile: Dockerfile
    ports:
      - "5003:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Zet de omgeving als Development (optioneel)