# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Navigate to project directory
      run: cd TaskSystem  # Navigeer naar de map waar je .sln-bestand zich bevindt

    - name: Restore dependencies
      run: dotnet restore TaskService.sln  # Voer restore uit op de .sln

    - name: Build
      run: dotnet build TaskService.sln --no-restore  # Bouw de oplossing

    - name: Test
      run: dotnet test TaskService.sln --no-build --verbosity normal  # Voer tests uit


