name: CI/CD with SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout de code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Setup Java (voor UserService)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Restore dependencies voor .NET-services
      - name: Restore dependencies for TaskService
        run: dotnet restore TaskSystem/TaskService.sln

      - name: Restore dependencies for NotificationService
        run: dotnet restore NotificationService/NotificationService.sln

      # Restore dependencies en build voor UserService (Java)
      - name: Restore dependencies for UserService (Java)
        run: mvn dependency:resolve
        working-directory: UserService

      # Build alle services
      - name: Build TaskService
        run: dotnet build TaskSystem/TaskService.sln --no-restore

      - name: Build NotificationService
        run: dotnet build NotificationService/NotificationService.sln --no-restore

      - name: Build UserService (Java)
        run: mvn clean package
        working-directory: UserService

  test:
    runs-on: ubuntu-latest
    needs: build  # Zorg ervoor dat de 'build' job succesvol is voordat deze wordt uitgevoerd
    steps:
      # Checkout de code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Test de services
      - name: Test TaskService
        run: dotnet test TaskSystem/TaskService.sln --no-build --verbosity normal

      - name: Test NotificationService
        run: dotnet test NotificationService/NotificationService.sln --no-build --verbosity normal

      - name: Test UserService (Java)
        run: mvn test
        working-directory: UserService

      - name: Check Prometheus alerts
        run: |
          response=$(curl -s https://e539-62-250-39-117.ngrok-free.app/api/v1/alerts)
          if [[ $(echo $response | jq '.data.alerts | length') -gt 0 ]]; then
            echo "There are active alerts!"
            exit 1  # Fail de pipeline
          else
            echo "No active alerts."
          fi

  docker_push:
    runs-on: ubuntu-latest
    needs: test  # Zorg ervoor dat de 'test' job succesvol is voordat deze wordt uitgevoerd
    steps:
      # Checkout de code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Log in bij Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker images
      - name: Build Docker image for TaskService
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/taskservice-taskservice:latest \
          -f TaskSystem/TaskService/Dockerfile TaskSystem/

      - name: Build Docker image for NotificationService
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/taskservice-notificationservice:latest ./NotificationService/NotificationService

      - name: Build Docker image for UserService
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/taskservice-userservice:latest ./UserService

      - name: Push RabbitMQ image to Docker Hub
        run: |
          docker pull rabbitmq:3-management
          docker tag rabbitmq:3-management ${{ secrets.DOCKER_USERNAME }}/rabbitmq-custom:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rabbitmq-custom:latest

      # Push Docker images naar Docker Hub
      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/taskservice-taskservice:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/taskservice-notificationservice:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/taskservice-userservice:latest

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=snyk.sarif
      - name: Print Snyk Sarif File
        run: cat snyk.sarif

      # Deploy Docker images to Docker Desktop
      - name: Deploy Docker images locally
        run: |
          # Stop and remove any running containers with the same name
          docker rm -f taskservice notificationservice userservice rabbitmq || true

          # Run RabbitMQ container
          docker run -d --name rabbitmq -p 15672:15672 -p 5672:5672 \
          ${{ secrets.DOCKER_USERNAME }}/rabbitmq-custom:latest

          # Run TaskService container
          docker run -d --name taskservice -p 5001:80 \
          ${{ secrets.DOCKER_USERNAME }}/taskservice-taskservice:latest

          # Run NotificationService container
          docker run -d --name notificationservice -p 5002:80 \
          ${{ secrets.DOCKER_USERNAME }}/taskservice-notificationservice:latest

          # Run UserService container
          docker run -d --name userservice -p 5003:80 \
          ${{ secrets.DOCKER_USERNAME }}/taskservice-userservice:latest
