name: SonarCloud .NET Scan

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  sonarcloud:
    name: SonarCloud Analysis for .NET
    runs-on: ubuntu-latest  

    steps:
      # Stap 1: Checkout de code
      - name: Checkout code
        uses: actions/checkout@v3

      # Stap 2: Stel .NET in (specifieke versie afhankelijk van je project)
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'  # Vervang door de versie die je gebruikt, bv. 7.0, 5.0, etc.

      # Stap 3: Restore de dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Stap 4: Bouw het project
      - name: Build project
        run: dotnet build --no-restore

      # Stap 5: Voer de SonarCloud-analyse uit
      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: TaskSystem  
          token: ${{ secrets.SONAR_TOKEN }}  
          projectKey: TaskSystem_TaskService  
          projectName: TaskService  
          args: > 
            -Dsonar.projectKey=TaskSystem_TaskService  
            -Dsonar.sources=TaskSystem/TaskService  
          
     
